server:
  port: 8989


spring:
  application:
    name: GATEWAY
  cloud:
    gateway:

      discovery:
        locator:
          enabled: true

          lower-case-service-id: true








logging:
  level:
    org.springframework.cloud.gateway: INFO
    reactor.netty.http.client: INFO
    root: INFO
    com.serjnn: INFO







